export default [
  {
    id: 1,
    title: "Anzughose mit Schlitz hinten",
    image: "/public/img/Anzughose mit Schlitz hinten.jpg",
    price: 5299,
    produktgruppe: "Hosen",
    sale: false,
    color: "grau",
    mostWanted: true,
    new: true,
  },
  {
    id: 2,
    title: "Asymmetrisches kurzes Kleid mit dünnen Trägern",
    image: "/public/img/Asymmetrisches kurzes Kleid mit dünnen Trägern.jpg",
    price: 3299,
    produktgruppe: "Kleider",
    sale: true,
    color: "schwarz",
    mostWanted: false,
    new: false,
  },
  {
    id: 3,
    title: "Baumwollbluse mit gesmockter Taille",
    image: "/public/img/Baumwollbluse mit gesmockter Taille.jpg",
    price: 3099,
    produktgruppe: "Blusen",
    sale: false,
    color: "beige",
    mostWanted: true,
    new: true,
  },
  {
    id: 4,
    title: "Bluse mit Zierfalten und Trompetenärmeln",
    image: "/public/img/Bluse mit Zierfalten und Trompetenärmeln.jpg",
    price: 2099,
    produktgruppe: "Blusen",
    sale: true,
    color: "Braun",
    mostWanted: true,
    new: false,
  },
  {
    id: 5,
    title: "Cropped Stricktop",
    image: "/public/img/Cropped Stricktop.jpg",
    price: 1999,
    produktgruppe: "Shirts",
    sale: true,
    color: "orange",
    mostWanted: false,
    new: false,
  },
  {
    id: 6,
    title: "Cropped-Strickpullover mit Rundhalsausschnitt",
    image: "/public/img/Cropped-Strickpullover mit Rundhalsausschnitt.jpg",
    price: 4299,
    produktgruppe: "Pullover",
    sale: false,
    color: "beige",
    mostWanted: true,
    new: false,
  },
  {
    id: 7,
    title: "Dropped-Shoulder-Strickjacke mit Knöpfen",
    image: "/public/img/Dropped-Shoulder-Strickjacke mit Knöpfen",
    price: 3399,
    produktgruppe: "Pullover",
    sale: true,
    color: "beige",
    mostWanted: false,
    new: false,
  },
  {
    id: 8,
    title: "Drop-Shoulder Strickoberteil",
    image: "/public/img/Drop-Shoulder Strickoberteil.jpg",
    price: 4899,
    produktgruppe: "Pullover",
    sale: false,
    color: "rot",
    mostWanted: true,
    new: false,
  },
  {
    id: 9,
    title: "Geripptes Unterhemd mit rundem Ausschnitt aus ökologischem Material",
    image: "/public/img/Geripptes Unterhemd mit rundem Ausschnitt aus ökologischem Material.jpg",
    price: 1599,
    produktgruppe: "Shirts",
    sale: true,
    color: "beige",
    mostWanted: true,
    new: false,
  },
  {
    id: 10,
    title: "Klassische Anzughose",
    image: "/public/img/Klassische Anzughose.jpg",
    price: 4899,
    produktgruppe: "Hosen",
    sale: false,
    color: "pink",
    mostWanted: false,
    new: true,
  },
  {
    id: 11,
    title: "Kurzärmeliges Minikleid mit offenem Rücken",
    image: "/public/img/Kurzärmeliges Minikleid mit offenem Rücken.jpg",
    price: 4299,
    produktgruppe: "Kleider",
    sale: false,
    color: "bunt",
    mostWanted: true,
    new: true,
  },
  {
    id: 12,
    title: "Kurze Lurex-Strickjacke",
    image: "/public/img/Kurze Lurex-Strickjacke.jpg",
    price: 3899,
    produktgruppe: "Pullover",
    sale: true,
    color: "rot",
    mostWanted: false,
    new: false,
  },
  {
    id: 13,
    title: "Kurze Melange-Anzughose",
    image: "/public/img/Kurze Melange-Anzughose.jpg",
    price: 5299,
    produktgruppe: "Hosen",
    sale: false,
    color: "blau",
    mostWanted: false,
    new: true,
  },
  {
    id: 14,
    title: "Kurzes geripptes Shirt mit langen Ärmeln",
    image: "/public/img/Kurzes geripptes Shirt mit langen Ärmeln.jpg",
    price: 2299,
    produktgruppe: "Shirts",
    sale: true,
    color: "pink",
    mostWanted: true,
    new: false,
  },
  {
    id: 15,
    title: "Kurzes geripptes Top mit langen Ärmeln",
    image: "/public/img/Kurzes geripptes Top mit langen Ärmeln.jpg",
    price: 2899,
    produktgruppe: "Shirts",
    sale: false,
    color: "beige",
    mostWanted: false,
    new: false,
  },
  {
    id: 16,
    title: "Kurzes Top mit Mesh-Detail",
    image: "/public/img/Kurzes Top mit Mesh-Detail.jpg",
    price: 2199,
    produktgruppe: "Shirts",
    sale: false,
    color: "schwarz",
    mostWanted: true,
    new: true,
  },
  {
    id: 17,
    title: "Langärmliges geripptes Bio-Oberteil mit V-Ausschnitt",
    image: "/public/img/Langärmliges geripptes Bio-Oberteil mit V-Ausschnitt.jpg",
    price: 3399,
    produktgruppe: "Shirts",
    sale: false,
    color: "schwarz",
    mostWanted: false,
    new: true,
  },
  {
    id: 18,
    title: "Lange, gerade geschnittene Hose aus Leinenmischung",
    image: "/public/img/Lange, gerade geschnittene Hose aus Leinenmischung.jpg",
    price: 4899,
    produktgruppe: "Hosen",
    sale: false,
    color: "weiß",
    mostWanted: true,
    new: false,
  },
  {
    id: 19,
    title: "Langes Trompetenärmel-Top",
    image: "/public/img/Langes Trompetenärmel-Top.jpg",
    price: 1899,
    produktgruppe: "Shirts",
    sale: true,
    color: "schwarz",
    mostWanted: true,
    new: false,
  },
  {
    id: 20,
    title: "Mid-Rise-PU-Hose",
    image: "/public/img/Mid-Rise-PU-Hose.jpg",
    price: 4899,
    produktgruppe: "Hosen",
    sale: false,
    color: "schwarz",
    mostWanted: false,
    new: true,
  },
  {
    id: 21,
    title: "Minikleid",
    image: "/public/img/Minikleid.jpg",
    price: 4899,
    produktgruppe: "Kleider",
    sale: false,
    color: "gelb",
    mostWanted: true,
    new: true,
  },
  {
    id: 22,
    title: "Neckholder-Bodysuit",
    image: "/public/img/Neckholder-Bodysuit.jpg",
    price: 2599,
    produktgruppe: "Hosen",
    sale: false,
    color: "schwarz",
    mostWanted: false,
    new: true,
  },
  {
    id: 23,
    title: "Organic geripptes Tank-Top",
    image: "/public/img/Organic geripptes Tank-Top.jpg",
    price: 1799,
    produktgruppe: "Shirts",
    sale: true,
    color: "grün",
    mostWanted: false,
    new: false,
  },
  {
    id: 24,
    title: "Organische farbige weiche steife weite Jeanshose",
    image: "/public/img/Organische farbige weiche steife weite Jeanshose.jpg",
    price: 4899,
    produktgruppe: "Hosen",
    sale: false,
    color: "gelb",
    mostWanted: false,
    new: false,
  },
  {
    id: 25,
    title: "Organische hohe Taille Roher Saum Gerade Jeans",
    image: "/public/img/Organische hohe Taille Roher Saum Gerade Jeans.jpg",
    price: 4299,
    produktgruppe: "Hosen",
    sale: false,
    color: "blau",
    mostWanted: true,
    new: true,
  },
  {
    id: 26,
    title: "Organische Skinny Jeans mit hoher Taille",
    image: "/public/img/Organische Skinny Jeans mit hoher Taille.jpg",
    price: 4099,
    produktgruppe: "Hosen",
    sale: false,
    color: "blau",
    mostWanted: false,
    new: true,
  },
  {
    id: 27,
    title: "Organischer Ripp-Strickpullover zum Wickeln",
    image: "/public/img/Organischer Ripp-Strickpullover zum Wickeln.jpg",
    price: 4099,
    produktgruppe: "Pullover",
    sale: false,
    color: "beige",
    mostWanted: true,
    new: true,
  },
  {
    id: 28,
    title: "Organischer Strickjacke mit Volumenärmeln",
    image: "/public/img/Organischer Strickjacke mit Volumenärmeln.jpg",
    price: 4899,
    produktgruppe: "Pullover",
    sale: false,
    color: "schwarz",
    mostWanted: true,
    new: true,
  },
  {
    id: 29,
    title: "Organischer, kurzer Strickpullover mit einem Rollkragen",
    image: "/public/img/Organischer, kurzer Strickpullover mit einem Rollkragen.jpg",
    price: 4299,
    produktgruppe: "Pullover",
    sale: false,
    color: "grau",
    mostWanted: true,
    new: true,
  },
  {
    id: 30,
    title: "Organisches Anglaise-UnterhemdOrganisches Anglaise-Unterhemd",
    image: "/public/img/Organisches Anglaise-UnterhemdOrganisches Anglaise-Unterhemd.jpg",
    price: 1399,
    produktgruppe: "Shirts",
    sale: true,
    color: "orange",
    mostWanted: true,
    new: false,
  },
  {
    id: 31,
    title: "Organisches Minikleid mit V-Ausschnitt",
    image: "/public/img/Organisches Minikleid mit V-Ausschnitt.jpg",
    price: 5599,
    produktgruppe: "Kleider",
    sale: false,
    color: "rot",
    mostWanted: true,
    new: false,
  },
  {
    id: 32,
    title: "Organisches Rüschentop",
    image: "/public/img/Organisches Rüschentop.jpg",
    price: 1899,
    produktgruppe: "Shirts",
    sale: true,
    color: "weiß",
    mostWanted: true,
    new: false,
  },
  {
    id: 33,
    title: "Recycelt gestrickt eingewickelt strickjacke",
    image: "/public/img/Recycelt gestrickt eingewickelt strickjacke.jpg",
    price: 4299,
    produktgruppe: "Pullover",
    sale: false,
    color: "grau",
    mostWanted: false,
    new: true,
  },
  {
    id: 34,
    title: "Recycelte Dobby-Bluse mit Volant",
    image: "/public/img/Recycelte Dobby-Bluse mit Volant.jpg",
    price: 3099,
    produktgruppe: "Blusen",
    sale: false,
    color: "pink",
    mostWanted: false,
    new: true,
  },
  {
    id: 35,
    title: "Recycelte gerippte Hose mit Schlitz",
    image: "/public/img/Recycelte gerippte Hose mit Schlitz.jpg",
    price: 5099,
    produktgruppe: "Hosen",
    sale: false,
    color: "schwarz",
    mostWanted: false,
    new: true,
  },
  {
    id: 36,
    title: "Recycelte Satinbluse Overlap",
    image: "/public/img/Recycelte Satinbluse Overlap.jpg",
    price: 3399,
    produktgruppe: "Blusen",
    sale: false,
    color: "schwarz",
    mostWanted: true,
    new: true,
  },
  {
    id: 37,
    title: "Recyceltes recyceltes Smock-Crop-Top",
    image: "/public/img/Recyceltes recyceltes Smock-Crop-Top.jpg",
    price: 3299,
    produktgruppe: "Shirts",
    sale: false,
    color: "rot",
    mostWanted: false,
    new: true,
  },
  {
    id: 38,
    title: "Recyceltes Strukturiertes Chiffon-Midikleid",
    image: "/public/img/Recyceltes Strukturiertes Chiffon-Midikleid.jpg",
    price: 5799,
    produktgruppe: "Kleider",
    sale: false,
    color: "grün",
    mostWanted: false,
    new: true,
  },
  {
    id: 39,
    title: "Recyceltes Wrap-Top",
    image: "/public/img/Recyceltes Wrap-Top.jpg",
    price: 1899,
    produktgruppe: "Shirts",
    sale: true,
    color: "schwarz",
    mostWanted: false,
    new: false,
  },
  {
    id: 40,
    title: "Rippoberteil mit tiefem Rundhalsausschnitt",
    image: "/public/img/Rippoberteil mit tiefem Rundhalsausschnitt.jpg",
    price: 3599,
    produktgruppe: "Pullover",
    sale: true,
    color: "schwarz",
    mostWanted: false,
    new: false,
  },
  {
    id: 41,
    title: "Strick-Cardigan mit Detail",
    image: "/public/img/Strick-Cardigan mit Detail.jpg",
    price: 4399,
    produktgruppe: "Pullover",
    sale: false,
    color: "beige",
    mostWanted: false,
    new: false,
  },
  {
    id: 42,
    title: "Strickpullover",
    image: "/public/img/Strickpullover.jpg",
    price: 5299,
    produktgruppe: "Pullover",
    sale: false,
    color: "gelb",
    mostWanted: true,
    new: false,
  },
  {
    id: 43,
    title: "Strukturiertes Kleid mit Kitteldetail",
    image: "/public/img/Strukturiertes Kleid mit Kitteldetail.jpg",
    price: 5099,
    produktgruppe: "Kleider",
    sale: false,
    color: "bunt",
    mostWanted: false,
    new: false,
  },
  {
    id: 44,
    title: "Strukturiertes Langarm-Shirt",
    image: "/public/img/Strukturiertes Langarm-Shirt.jpg",
    price: 5799,
    produktgruppe: "Shirts",
    sale: false,
    color: "blau",
    mostWanted: true,
    new: true,
  },
  {
    id: 45,
    title: "Strukturiertes Midikleid mit Körbchen",
    image: "/public/img/Strukturiertes Midikleid mit Körbchen.jpg",
    price: 5199,
    produktgruppe: "Kleider",
    sale: false,
    color: "rot",
    mostWanted: false,
    new: true,
  },
  {
    id: 46,
    title: "Top mit Rüschendetail",
    image: "/public/img/Top mit Rüschendetail.jpg",
    price: 2899,
    produktgruppe: "Shirts",
    sale: false,
    color: "schwarz",
    mostWanted: false,
    new: true,
  },
  {
    id: 47,
    title: "Twist-Ripp-Midikleid",
    image: "/public/img/Twist-Ripp-Midikleid.jpg",
    price: 5199,
    produktgruppe: "Kleider",
    sale: false,
    color: "schwarz",
    mostWanted: false,
    new: false,
  },
  {
    id: 48,
    title: "Weste Strickpullover",
    image: "/public/img/Weste Strickpullover.jpg",
    price: 4299,
    produktgruppe: "Pullover",
    sale: false,
    color: "gelb",
    mostWanted: true,
    new: true,
  },
];

export const categories = [
  { categoryId: 1, name: "Pullover" },
  { categoryId: 2, name: "Shirts" },
  { categoryId: 3, name: "Hosen" },
  { categoryId: 4, name: "Kleider" },
  { categoryId: 5, name: "Blumen" },
];
