export default [
  {
    id: 1,
    title: "Anzughose mit Schlitz hinten",
    image: "/img/Anzughose mit Schlitz hinten.jpg",
    price: 5299,
    produktgruppe: "Hosen",
    sale: false,
    color: 11,
    colorstring: "grau",
    mostWanted: false,
    new: false,
  },
  {
    id: 2,
    title: "Asymmetrisches kurzes Kleid mit dünnen Trägern",
    image: "/img/Asymmetrisches kurzes Kleid mit dünnen Trägern.jpg",
    price: 3299,
    produktgruppe: "Kleider",
    sale: true,
    color: 1,
    colorstring: "schwarz",
    mostWanted: true,
    new: false,
  },
  {
    id: 3,
    title: "Baumwollbluse mit gesmockter Taille",
    image: "/img/Baumwollbluse mit gesmockter Taille.jpg",
    price: 3099,
    produktgruppe: "Blusen",
    sale: false,
    color: 3,
    colorstring: "beige",
    mostWanted: true,
    new: true,
  },
  {
    id: 4,
    title: "Bluse mit Zierfalten und Trompetenärmeln",
    image: "/img/Bluse mit Zierfalten und Trompetenärmeln.jpg",
    price: 2099,
    produktgruppe: "Blusen",
    sale: true,
    color: 8,
    colorstring: "braun",
    mostWanted: true,
    new: false,
  },
  {
    id: 5,
    title: "Cropped Stricktop",
    image: "/img/Cropped Stricktop.jpg",
    price: 1999,
    produktgruppe: "Shirts",
    sale: true,
    color: 10,
    colorstring: "pink",
    mostWanted: false,
    new: false,
  },
  {
    id: 6,
    title: "Cropped-Strickpullover mit Rundhalsausschnitt",
    image: "/img/Cropped-Strickpullover mit Rundhalsausschnitt.jpg",
    price: 4299,
    produktgruppe: "Pullover",
    sale: false,
    color: 3,
    colorstring: "beige",
    mostWanted: true,
    new: false,
  },
  {
    id: 7,
    title: "Dropped-Shoulder-Strickjacke mit Knöpfen",
    image: "/img/Dropped-Shoulder-Strickjacke mit Knoepfen.jpg",
    price: 3399,
    produktgruppe: "Pullover",
    sale: true,
    color: 3,
    colorstring: "beige",
    mostWanted: false,
    new: false,
  },
  {
    id: 8,
    title: "Drop-Shoulder Strickoberteil",
    image: "/img/Drop-Shoulder Strickoberteil.jpg",
    price: 4899,
    produktgruppe: "Pullover",
    sale: false,
    color: 12,
    colorstring: "grau",
    mostWanted: true,
    new: false,
  },
  {
    id: 9,
    title: "Geripptes Unterhemd mit rundem Ausschnitt aus ökologischem Material",
    image: "/img/Geripptes Unterhemd mit rundem Ausschnitt aus ökologischem Material.jpg",
    price: 1599,
    produktgruppe: "Shirts",
    sale: true,
    color: 3,
    colorstring: "beige",
    mostWanted: true,
    new: false,
  },
  {
    id: 10,
    title: "Klassische Anzughose",
    image: "/img/Klassische Anzughose.jpg",
    price: 4899,
    produktgruppe: "Hosen",
    sale: false,
    color: 10,
    colorstring: "pink",
    mostWanted: false,
    new: true,
  },
  {
    id: 11,
    title: "Kurzärmeliges Minikleid mit offenem Rücken",
    image: "/img/Kurzärmeliges Minikleid mit offenem Rücken.jpg",
    price: 4299,
    produktgruppe: "Kleider",
    sale: false,
    color: 7,
    colorstring: "bunt",
    mostWanted: true,
    new: true,
  },
  {
    id: 12,
    title: "Kurze Lurex-Strickjacke",
    image: "/img/Kurze Lurex-Strickjacke.jpg",
    price: 3899,
    produktgruppe: "Pullover",
    sale: true,
    color: 12,
    colorstring: "rot",
    mostWanted: false,
    new: false,
  },
  {
    id: 13,
    title: "Kurze Melange-Anzughose",
    image: "/img/Kurze Melange-Anzughose.jpg",
    price: 5299,
    produktgruppe: "Hosen",
    sale: false,
    color: 6,
    colorstring: "blau",
    mostWanted: false,
    new: true,
  },
  {
    id: 14,
    title: "Kurzes geripptes Shirt mit langen Ärmeln",
    image: "/img/Kurzes geripptes Shirt mit langen Ärmeln.jpg",
    price: 2299,
    produktgruppe: "Shirts",
    sale: true,
    color: 10,
    colorstring: "pink",
    mostWanted: true,
    new: false,
  },
  {
    id: 15,
    title: "Kurzes geripptes Top mit langen Ärmeln",
    image: "/img/Kurzes geripptes Top mit langen Ärmeln.jpg",
    price: 2899,
    produktgruppe: "Shirts",
    sale: false,
    color: 3,
    colorstring: "beige",
    mostWanted: false,
    new: false,
  },
  {
    id: 16,
    title: "Kurzes Top mit Mesh-Detail",
    image: "/img/Kurzes Top mit Mesh-Detail.jpg",
    price: 2199,
    produktgruppe: "Shirts",
    sale: false,
    color: 1,
    colorstring: "schwarz",
    mostWanted: true,
    new: true,
  },
  {
    id: 17,
    title: "Langärmliges geripptes Bio-Oberteil mit V-Ausschnitt",
    image: "/img/Langärmliges geripptes Bio-Oberteil mit V-Ausschnitt.jpg",
    price: 3399,
    produktgruppe: "Shirts",
    sale: false,
    color: 1,
    colorstring: "schwarz",
    mostWanted: false,
    new: true,
  },
  {
    id: 18,
    title: "Lange, gerade geschnittene Hose aus Leinenmischung",
    image: "/img/Lange, gerade geschnittene Hose aus Leinenmischung.jpg",
    price: 4899,
    produktgruppe: "Hosen",
    sale: false,
    color: 2,
    colorstring: "weiß",
    mostWanted: true,
    new: false,
  },
  {
    id: 19,
    title: "Langes Trompetenärmel-Top",
    image: "/img/Langes Trompetenärmel-Top.jpg",
    price: 1899,
    produktgruppe: "Shirts",
    sale: true,
    color: 1,
    colorstring: "schwarz",
    mostWanted: true,
    new: false,
  },
  {
    id: 20,
    title: "Mid-Rise-PU-Hose",
    image: "/img/Mid-Rise-PU-Hose.jpg",
    price: 4899,
    produktgruppe: "Hosen",
    sale: false,
    color: 1,
    colorstring: "schwarz",
    mostWanted: false,
    new: true,
  },
  {
    id: 21,
    title: "Minikleid",
    image: "/img/Minikleid.jpg",
    price: 4899,
    produktgruppe: "Kleider",
    sale: false,
    color: 4,
    colorstring: "gelb",
    mostWanted: true,
    new: true,
  },
  {
    id: 22,
    title: "Neckholder-Bodysuit",
    image: "/img/Neckholder-Bodysuit.jpg",
    price: 2599,
    produktgruppe: "Shirts",
    sale: false,
    color: 7,
    colorstring: "bunt",
    mostWanted: false,
    new: true,
  },
  {
    id: 23,
    title: "Organic geripptes Tank-Top",
    image: "/img/Organic geripptes Tank-Top.jpg",
    price: 1799,
    produktgruppe: "Shirts",
    sale: true,
    color: 9,
    colorstring: "grün",
    mostWanted: false,
    new: false,
  },
  {
    id: 24,
    title: "Organische farbige weiche steife weite Jeanshose",
    image: "/img/Organische farbige weiche steife weite Jeanshose.jpg",
    price: 4899,
    produktgruppe: "Hosen",
    sale: false,
    color: 4,
    colorstring: "gelb",
    mostWanted: false,
    new: false,
  },
  {
    id: 25,
    title: "Organische hohe Taille Roher Saum Gerade Jeans",
    image: "/img/Organische hohe Taille Roher Saum Gerade Jeans.jpg",
    price: 4299,
    produktgruppe: "Hosen",
    sale: false,
    color: 6,
    colorstring: "blau",
    mostWanted: true,
    new: true,
  },
  {
    id: 26,
    title: "Organische Skinny Jeans mit hoher Taille",
    image: "/img/Organische Skinny Jeans mit hoher Taille.jpg",
    price: 4099,
    produktgruppe: "Hosen",
    sale: false,
    color: 6,
    colorstring: "blau",
    mostWanted: false,
    new: true,
  },
  {
    id: 27,
    title: "Organischer Ripp-Strickpullover zum Wickeln",
    image: "/img/Organischer Ripp-Strickpullover zum Wickeln.jpg",
    price: 4099,
    produktgruppe: "Pullover",
    sale: false,
    color: 3,
    colorstring: "beige",
    mostWanted: true,
    new: true,
  },
  {
    id: 28,
    title: "Organischer Strickjacke mit Volumenärmeln",
    image: "/img/Organischer Strickjacke mit Volumenärmeln.jpg",
    price: 4899,
    produktgruppe: "Pullover",
    sale: false,
    color: 1,
    colorstring: "schwarz",
    mostWanted: true,
    new: true,
  },
  {
    id: 29,
    title: "Organischer, kurzer Strickpullover mit einem Rollkragen",
    image: "/img/Organischer, kurzer Strickpullover mit einem Rollkragen.jpg",
    price: 4299,
    produktgruppe: "Pullover",
    sale: false,
    color: 11,
    colorstring: "grau",
    mostWanted: true,
    new: true,
  },
  {
    id: 30,
    title: "Organisches Anglaise-UnterhemdOrganisches Anglaise-Unterhemd",
    image: "/img/Organisches Anglaise-UnterhemdOrganisches Anglaise-Unterhemd.jpg",
    price: 1399,
    produktgruppe: "Shirts",
    sale: true,
    color: 5,
    colorstring: "orange",
    mostWanted: true,
    new: false,
  },
  {
    id: 31,
    title: "Organisches Minikleid mit V-Ausschnitt",
    image: "/img/Organisches Minikleid mit V-Ausschnitt.jpg",
    price: 5599,
    produktgruppe: "Kleider",
    sale: false,
    color: 12,
    colorstring: "rot",
    mostWanted: true,
    new: false,
  },
  {
    id: 32,
    title: "Organisches Rüschentop",
    image: "/img/Organisches Rüschentop.jpg",
    price: 1899,
    produktgruppe: "Shirts",
    sale: true,
    color: 2,
    colorstring: "weiß",
    mostWanted: true,
    new: false,
  },
  {
    id: 33,
    title: "Recycelt gestrickt eingewickelt strickjacke",
    image: "/img/Recycelt gestrickt eingewickelt strickjacke.jpg",
    price: 4299,
    produktgruppe: "Pullover",
    sale: false,
    color: 11,
    colorstring: "grau",
    mostWanted: false,
    new: true,
  },
  {
    id: 34,
    title: "Recycelte Dobby-Bluse mit Volant",
    image: "/img/Recycelte Dobby-Bluse mit Volant.jpg",
    price: 3099,
    produktgruppe: "Blusen",
    sale: false,
    color: 10,
    colorstring: "pink",
    mostWanted: false,
    new: true,
  },
  {
    id: 35,
    title: "Recycelte gerippte Hose mit Schlitz",
    image: "/img/Recycelte gerippte Hose mit Schlitz.jpg",
    price: 5099,
    produktgruppe: "Hosen",
    sale: false,
    color: 1,
    colorstring: "schwarz",
    mostWanted: false,
    new: true,
  },
  {
    id: 36,
    title: "Recycelte Satinbluse Overlap",
    image: "/img/Recycelte Satinbluse Overlap.jpg",
    price: 3399,
    produktgruppe: "Blusen",
    sale: false,
    color: 1,
    colorstring: "schwarz",
    mostWanted: true,
    new: true,
  },
  {
    id: 37,
    title: "Recyceltes recyceltes Smock-Crop-Top",
    image: "/img/Recyceltes recyceltes Smock-Crop-Top.jpg",
    price: 3299,
    produktgruppe: "Shirts",
    sale: false,
    color: 12,
    colorstring: "rot",
    mostWanted: false,
    new: true,
  },
  {
    id: 38,
    title: "Recyceltes Strukturiertes Chiffon-Midikleid",
    image: "/img/Recyceltes Strukturiertes Chiffon-Midikleid.jpg",
    price: 5799,
    produktgruppe: "Kleider",
    sale: false,
    color: 9,
    colorstring: "grün",
    mostWanted: false,
    new: true,
  },
  {
    id: 39,
    title: "Recyceltes Wrap-Top",
    image: "/img/Recyceltes Wrap-Top.jpg",
    price: 1899,
    produktgruppe: "Shirts",
    sale: true,
    color: 1,
    colorstring: "schwarz",
    mostWanted: false,
    new: false,
  },
  {
    id: 40,
    title: "Rippoberteil mit tiefem Rundhalsausschnitt",
    image: "/img/Rippoberteil mit tiefem Rundhalsausschnitt.jpg",
    price: 3599,
    produktgruppe: "Pullover",
    sale: true,
    color: 1,
    colorstring: "schwarz",
    mostWanted: false,
    new: false,
  },
  {
    id: 41,
    title: "Strick-Cardigan mit Detail",
    image: "/img/Strick-Cardigan mit Detail.jpg",
    price: 4399,
    produktgruppe: "Pullover",
    sale: false,
    color: 8,
    colorstring: "braun",
    mostWanted: false,
    new: false,
  },
  {
    id: 42,
    title: "Strickpullover",
    image: "/img/Strickpullover.jpg",
    price: 5299,
    produktgruppe: "Pullover",
    sale: false,
    color: 4,
    colorstring: "gelb",
    mostWanted: true,
    new: false,
  },
  {
    id: 43,
    title: "Strukturiertes Kleid mit Kitteldetail",
    image: "/img/Strukturiertes Kleid mit Kitteldetail.jpg",
    price: 5099,
    produktgruppe: "Kleider",
    sale: false,
    color: 7,
    colorstring: "bunt",
    mostWanted: false,
    new: false,
  },
  {
    id: 44,
    title: "Strukturiertes Langarm-Shirt",
    image: "/img/Strukturiertes Langarm-Shirt.jpg",
    price: 5799,
    produktgruppe: "Shirts",
    sale: false,
    color: 6,
    colorstring: "blau",
    mostWanted: true,
    new: true,
  },
  {
    id: 45,
    title: "Strukturiertes Midikleid mit Körbchen",
    image: "/img/Strukturiertes Midikleid mit Körbchen.jpg",
    price: 5199,
    produktgruppe: "Kleider",
    sale: false,
    color: 12,
    colorstring: "rot",
    mostWanted: false,
    new: true,
  },
  {
    id: 46,
    title: "Top mit Rüschendetail",
    image: "/img/Top mit Rüschendetail.jpg",
    price: 2899,
    produktgruppe: "Shirts",
    sale: false,
    color: 1,
    colorstring: "schwarz",
    mostWanted: false,
    new: true,
  },
  {
    id: 47,
    title: "Twist-Ripp-Midikleid",
    image: "/img/Twist-Ripp-Midikleid.jpg",
    price: 5199,
    produktgruppe: "Kleider",
    sale: false,
    color: 1,
    colorstring: "schwarz",
    mostWanted: false,
    new: false,
  },
  {
    id: 48,
    title: "Weste Strickpullover",
    image: "/img/Weste Strickpullover.jpg",
    price: 4299,
    produktgruppe: "Pullover",
    sale: false,
    color: 4,
    colorstring: "gelb",
    mostWanted: true,
    new: true,
  },
];

export const colors = [
  { id: 1, name: "schwarz" },
  { id: 2, name: "weiß" },
  { id: 3, name: "beige" },
  { id: 4, name: "gelb" },
  { id: 5, name: "orange" },
  { id: 6, name: "blau" },
  { id: 7, name: "bunt" },
  { id: 8, name: "braun" },
  { id: 9, name: "grün" },
  { id: 10, name: "pink" },
  { id: 11, name: "grau" },
  { id: 12, name: "rot" },
];
